### ISSUE TITLE
nutNullable?

### ISSUE THREAD

**Issue by NightingaleM** [EmadFani/adonisjs-vscode-snippet#1]
![image](https://user-images.githubusercontent.com/25434464/44776035-b3d98580-aba9-11e8-9958-e01aaac6c646.png)

**Comment by EmadFani** [comment]
well sorry about it i just made this snippet in less that 30 minutes so it's buggy and i didn't think that a day will come that ppl will use it sorry about the bugs i will fix theme and add more snippets to it

**Comment by EmadFani** [comment]
removed
